version: 2

workflows:
  version: 2
  build_test_release:
    jobs:
      - botscripten
      - release:
          requires:
            - botscripten
          filters:
            branches:
              only:
                - master
                - next
                - beta

# ######################################################################
# Job Definitions
# Each job is keyed with a unique name, and sequenced in the workflows
# section. Should any run step fail within a job, then that step will be
# marked as a failure
# ######################################################################
jobs:
  botscripten:
    docker:
      - image: "circleci/node:latest"
    working_directory: ~/botscripten
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm run ci
  release:
    docker:
      - image: "circleci/node:latest"
    working_directory: ~/botscripten
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm run build
      - run:
          name: performing semantic-release
          command: npm run release || true
