name: Semantic Release
on:
  push:
    branches:
      - next
      - beta
      - master
jobs:
  semantic_release:
    name: Build, Test, Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.1
      - name: Installing Dependencies
        run: npm ci --quiet --no-progress
      - name: Building
        run: npm run build
      - name: Testing & Certifying
        run: npm run ci
      - name: Releasing
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} #required for writing CHANGELOG to protected branch
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
